<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MediaLock</AssemblyName>
    <Product>Media Lock</Product>
    <Version>0.2.0-rc.2</Version>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <FileVersion>0.2.0.0</FileVersion>
    <InformationalVersion>0.2.0-rc.2</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaLock.Application\MediaLock.Application.csproj" />
    <ProjectReference Include="..\MediaLock.Core\MediaLock.Core.csproj" />
    <ProjectReference Include="..\MediaLock.Windows\MediaLock.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MediaLock.App.Tests" />
  </ItemGroup>

</Project>
